import PrimaryNavigationBar from "@/components/navigation_bars/PrimaryNavigationBar";

import "../scss/styles.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PrimaryNavigationBar />
        {children}
      </body>
    </html>
  );
}
